#! /usr/bin/env python3


def problem_2(n = 4000000):
    """
       Project Euler Problem 2
       
       Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
       By starting with 1 and 2, the first 10 terms will be:
       
       1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
       
       By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
       find the sum of the even-valued terms.
    """
  
    fib_a = 1
    fib_b = 1
    fib_i = 2
  
    even_sum = 0
    while fib_i < n:
        even_sum += fib_i
        fib_a = fib_i + fib_b
        fib_b = fib_a + fib_i
        fib_i = fib_a + fib_b
        
    return even_sum


PROBLEM_STATEMENT = "Project Euler Problem 2\n\n\tEach new term in the Fibonacci sequence is generated by adding the previous two terms.\n\tBy starting with 1 and 2, the first 10 terms will be:\n\n\t1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n\n\tBy considering the terms in the Fibonacci sequence whose values do not exceed four million, \n\tfind the sum of the even-valued terms."

print(PROBLEM_STATEMENT)
print("\n\n" + str(problem_2()))
